### PR TITLE
Issue/688 nested paragraphs

### LINKED ISSUE #688: Nested block can add a new empty paragraph after it
This was original reported for GB [here](https://github.com/wordpress-mobile/AztecEditor-Android/issues/686#issuecomment-393159018), but turned out to be a more general problem with the way Aztec handles nested block with paragraphs.

### Steps to repro
Start the demo app with the following content
```
<div>
 <p>first paragraph</p>
</div>
<p>second par</p>
```
Then switch the demo app to HTML mode.
The output is the following
```
<div>
 <p>first paragraph</p>
</div>
<p></p>
<p>second par</p>
```

As you can see there is a new `p` element in between those 2 original 1st level element.

### PR DESCRIPTION
**Pull request by 0nko**
Fixes #688.

**Steps to verify**
1. Start the demo app with the following content:
```
<div>
 <p>first paragraph</p>
</div>
<p>second par</p>
```
2. Then switch the demo app to HTML mode.
3. The output is the same as input

### CODE REVIEW

**Comment by mzorz** [comment]
This is so cool thanks @ondrej! Will test and review later :ok_hand: :bow:

**Comment by daniloercoli** [comment]
Looks good to me. 
Mario, feel free to merge this if it's OK for you.

**Comment by mzorz** [comment]
Running tests, will merge afterwards 👍

**Comment by mzorz** [comment]
:shipit:

**Pull request merged**
