### PR TITLE
Use default WordPress video shortcode for quick testing

### PR DESCRIPTION
**Pull request by daniloercoli**
This PR basically changes the HTML produced by `AztecVideoSpan`, and prints out the `[video]` default WP shortcode Ref: https://codex.wordpress.org/Video_Shortcode instead of the HTML `video` tag.

This is a quick fix to make video upload working in wp-android, to be used until a full shortcode support is completed in Aztec.

### CODE REVIEW

**Comment by 0nko** [comment]
This works fine when you first add a video but it only shows `[video...]` afterwards.

If you add `source = source.replaceAll("\\[(video.*)\\]", "<$1>");` before the [parse()](https://github.com/wordpress-mobile/AztecEditor-Android/blob/develop/aztec/src/main/java/org/wordpress/aztec/Html.java#L228) call, the video span will render properly in visual mode for the existing videos, too.

**Comment by daniloercoli** [comment]
Cool thanks, will add it shortly!

**Comment by daniloercoli** [comment]
It seems that the correct regexp is the following: `source = source.replaceAll("\\[video([^\\]]*)\\]", "<video$1/>");`

The one proposed above doesn't work if you have more than one video, and doesn't close the video tag, duplicating all the videos if you switch between visual mode and text mode multiple times.

**Comment by daniloercoli** [comment]
This should be ready for another round of testing.

**Comment by 0nko** [comment]
Good catch, I just quickly tried that regex :).

:shipit:

**Pull request merged**
