### PR TITLE
Updated UI tests

### PR DESCRIPTION
**Pull request by MatisseHack**
* Updated UI tests to use the page object pattern
* Added image tests
* Added mixed list test

### Test
1. Run all tests in androidTest

### CODE REVIEW

**Comment by 0nko** [comment]
When I run the unit tests, `testMixedList()` is failing because the expected value doesn't reflect the actual behavior. When you tap a single item in a list and change the list type, the entire list changes, which is the correct way.

**Comment by MatisseHack** [comment]
I was under the impression that only the list item(s) selected should change type. If the whole list should change, then that is inconsistent with iOS. Not sure which is correct, but it's an easy fix either way.

cc @aerych

**Comment by aerych** [comment]
Thanks @0nko.  @MatisseHack if its no trouble could we update the test as @0nko described?

**Comment by MatisseHack** [comment]
No trouble at all

**Comment by 0nko** [comment]
Thanks @MatisseHack! Looks good. I'll go ahead and merge this.

:shipit:

**Comment by aerych** [comment]
Thank you @0nko & @MatisseHack :)

**Pull request merged**
