### PR TITLE
Add possibility to use a custom layout for the toolbar

### PR DESCRIPTION
**Pull request by starshipcoder**
Permits to ui client to change icon order, hide icon, use 2 lines...

### CODE REVIEW

**Comment by maxme** [comment]
Just a note that we're changing the project license, since this haven't landed yet it's not a problem, but if the patch land after the switch, it will be done under the MPL v2.

Ref. https://github.com/wordpress-mobile/AztecEditor-Android/pull/922

**Comment by starshipcoder** [comment]
No problem for me, it is even better!

**Comment by maxme** [comment]
@starshipcoder that works fine, but the logic is a bit weird to me. What about keeping the `advanced` option and add a `customLayout` attribute that, if set, would override the `advanced` option. 

I think @anitaa1990 worked on that, what's your opinion about this one?

**Comment by starshipcoder** [comment]
You are right ! I will do that. Thank you for the review

**Comment by anitaa1990** [comment]
> @starshipcoder that works fine, but the logic is a bit weird to me. What about keeping the advanced option and add a customLayout attribute that, if set, would override the advanced option.
I think @anitaa1990 worked on that, what's your opinion about this one?

That sounds like a good idea to me!

**Comment by dimanych** [comment]
Please 👍 and merge this pr )

**Comment by starshipcoder** [comment]
I apply @maxme suggestion, would you mind review the PR ?

**Comment by oguzkocer** [comment]
@anitaa1990 It looks like this PR might have slipped through the cracks, could you take a look at it when you get a chance?

**Comment by anitaa1990** [comment]
I can take a look at this one today 👍

**Review by anitaa1990 — APPROVED** [review]
This looks good! Thank you for working on this @starshipcoder. :shipit:

**Comment by anitaa1990** [comment]
@oguzkocer there are a few checks failing in the PR (related to Buildkite). Is there something I need to do (maybe create the same branch `customize_toolbar_layout` in order to reinitiate the checks again?

**Comment by oguzkocer** [comment]
@anitaa1990 The CI checks don't work in forked PRs, a separate PR needs to be created to run the checks. I'll send you a Slack message with a link to a guide for this.

**Pull request merged**
