### PR TITLE
Issue/fix block styling of empty lines

### LINKED ISSUE #418: Crash report 7.8: RuntimeException in BlockFormatter.toggleQuote
```
Fatal Exception: java.lang.RuntimeException: PARAGRAPH span must start at paragraph boundary
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:638)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:626)
       at org.wordpress.aztec.handlers.BlockHandler$Companion.set(BlockHandler.kt:112)
       at org.wordpress.aztec.formatting.BlockFormatter.applyBlock(BlockFormatter.kt:423)
       at org.wordpress.aztec.formatting.BlockFormatter.applyBlockStyle(BlockFormatter.kt:362)
       at org.wordpress.aztec.formatting.BlockFormatter.applyBlockStyle$default(BlockFormatter.kt:329)
       at org.wordpress.aztec.formatting.BlockFormatter.toggleQuote(BlockFormatter.kt:46)
       at org.wordpress.aztec.AztecText.toggleFormatting(AztecText.kt:613)
       at org.wordpress.aztec.toolbar.AztecToolbar.onToolbarAction(AztecToolbar.kt:430)
       at org.wordpress.aztec.toolbar.AztecToolbar.access$onToolbarAction(AztecToolbar.kt:24)
       at org.wordpress.aztec.toolbar.AztecToolbar$initView$1.onClick(AztecToolbar.kt:338)
       at android.view.View.performClick(View.java:4858)
       at android.widget.CompoundButton.performClick(CompoundButton.java:120)
       at android.view.View$PerformClick.run(View.java:20329)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5950)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:987)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
```

### PR DESCRIPTION
**Pull request by khaykov**
Fixes #418 (and bunch of related functionality)

This PR fixes block styling in ambiguous situations. Apparently, people style all kind of weirdly selected text! 
The original issue happened when you applied quote to the selection that included \n at the end.
This was one of the many problems that were caused by issues in detecting the quote in selection, and bounds of the paragraphs.

There are a lot of scenarios where problems were happening, and I think I recreated all of them in tests.

### CODE REVIEW

**Comment by khaykov** [comment]
Good catch! Fixed.

**Comment by 0nko** [comment]
Nice, it works now. Another thing I tried was apply the quote to an empty list item. Each time a new nested blockquote gets created, it's never removed. Is that expected?

**Comment by khaykov** [comment]
>  Each time a new nested blockquote gets created, it's never removed. Is that expected?
I can't reproduce this one. Can you attach a screenshot of a text layout where this happens?

**Comment by 0nko** [comment]
Turns out I forgot to pull the last commit. 🤦‍♂️ Nevermind.

**Comment by 0nko** [comment]
Good job! 🎉 
:shipit:

**Pull request merged**
