### PR TITLE
Feature/rtl quote support

### PR DESCRIPTION
**Pull request by khaykov**
This PR adds a correct drawing of quote for RTL languages.

Drawing direction is determined based on the language of each individual line.

[https://gyazo.com/bceeb0352bc4f8d36e360a9300d447d4](https://gyazo.com/bceeb0352bc4f8d36e360a9300d447d4)

### CODE REVIEW

**Comment by malinajirka** [comment]
Thanks for the PR @khaykov ;)! It looks good, however I've found 2 issues.

1. No text in the quote - LtR locale
default_ltr
No text in the quote - RtL locale
deafult_rtl
When there isn't any text in the quote, it automatically fallbacks to LtR quote. Maybe we could pick `TextDirectionHeuristicsCompat.FIRSTSTRONG_LTR` vs `TextDirectionHeuristicsCompat.FIRSTSTRONG_RTL` depending on the default locale? I haven't tested it, it's just an idea. Btw the leading margin rectangle is missing on the second image.

2. On api level 18 the leading margin rectangle doesn't show up in RtL mode. leading_marign_sdk_18

**Comment by khaykov** [comment]
Good catch! I totally forgot to test empty quotes :) Defaulting to the locale is also a great idea - lists behave like this by default, so I change the quote to do it too.

**Comment by malinajirka** [comment]
Hmm, it still doesn't work as expected in some cases - I wasn't able to find any pattern, it seems random:D. When I checked the "text" string using the debugger it had length = 1 but appeared to be empty.
I've tried this code and it seems to work as expected. WDYT @khaykov ?
```
val textDirectionHeuristic: TextDirectionHeuristicCompat = 
if (TextUtilsCompat.getLayoutDirectionFromLocale(Locale.getDefault()) == ViewCompat.LAYOUT_DIRECTION_RTL) {
   TextDirectionHeuristicsCompat.FIRSTSTRONG_RTL
  } else {
   TextDirectionHeuristicsCompat.FIRSTSTRONG_LTR
 }
return textDirectionHeuristic.isRtl(text, start, end - start)```

**Comment by khaykov** [comment]
Hmm. Yes, it's weird. I noticed that it doesn't work for me every time too. I switched the `isRtlQuote` to your method, and looks like it works ok :) Thanks!

**Comment by malinajirka** [comment]
I'm glad it works;). Thanks!

**Pull request merged**
