### PR TITLE
Copy/paste Fix & Improvement

### LINKED ISSUE #424: Crash report 7.8: RuntimeException in AztecText.paste
```
Fatal Exception: java.lang.RuntimeException: PARAGRAPH span must start at paragraph boundary
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:688)
       at android.text.SpannableStringBuilder.change(SpannableStringBuilder.java:434)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:547)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:503)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:502)
       at org.wordpress.aztec.AztecText.paste(AztecText.kt:974)
       at org.wordpress.aztec.AztecText.onTextContextMenuItem(AztecText.kt:920)
       at android.widget.Editor$TextActionModeCallback.onActionItemClicked(Editor.java:3315)
       at com.android.internal.policy.PhoneWindow$DecorView$ActionModeCallback2Wrapper.onActionItemClicked(PhoneWindow.java:3617)
       at com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:85)
       at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:766)
       at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
       at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:909)
       at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:899)
       at com.android.internal.view.FloatingActionMode$4.onMenuItemClick(FloatingActionMode.java:111)
       at com.android.internal.widget.FloatingToolbar$FloatingToolbarMainPanel$1.onClick(FloatingToolbar.java:1018)
       at android.view.View.performClick(View.java:5265)
       at android.view.View$PerformClick.run(View.java:21534)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5728)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

### PR DESCRIPTION
**Pull request by 0nko**
Fixes #424, #447 and #285.

Summary of things this PR addressed:

- Fixes block element style copying: Headings, lists, quotes are now preserved.
- Copying now works across multiple list hierarchies: When copying inside a nested list, only the minimum required level gets copied. For example, copying a list item nested under 3 levels of lists will copy just the last one. 
- When pasting text next to an inline style, the pasted text is affected by the original text next to it.
- Copy/pasting of exotic unicode characters, such as non-Latin characters and emoji works now (those characters are not escaped anymore during parsing). 
- Copied Calypso paragraphs are also preserved now. 
- The paste logic now tries to look at the type of data being pasted. If it detects styled text (`Spanned`) or HTML, the data is parsed first and the styling is preserved. That means copying text from a website copies the HTML and all the headings, lists, typefaces are copied along.

### CODE REVIEW

**Comment by khaykov** [comment]
Great job! Copypasting feels like one of those rabbit holes. 
I'm still testing different scenarios, but so far a couple of things I noticed (but not sure if they are inside the scope of this PR or not):

- After pasting text the cursor is gone.
- Pasting text (regular text without any block style) ads new line around it.
- Inline formatting is not applied to text that is pasted before or after the styled text.
- History is not affected by pasting.
- Pasting Heading into heading adds an extra newline at the top.
- Pasting anything into the middle of heading splits it in half (this is expected) and the bottom half loses the style (unexpected).

**Comment by 0nko** [comment]
> - After pasting text the cursor is gone.

This is caused by the `refershText()` call during image loading. We can probably leave it for another PR.
> - Pasting text (regular text without any block style) ads new line around it.

I couldn't reproduce this. Did you turn off Calypso mode?

> - Inline formatting is not applied to text that is pasted before or after the styled text.

> - History is not affected by pasting.

This is now fixed.

> - Pasting Heading into heading adds an extra newline at the top.

It copies the original heading style, which means it's a "block" style and it is, therefore, surrounded by newlines. So the result is the same as parsing `<h1>Heading<h2>Heading 2</h2></h1>`. This is a tough one, because I'm just pasting HTML into HTML, which means I can't detect if the target location is inside a heading. And then the final HTML has both headings split already. Unless someone starts complaining about this, I'd say we leave this :P.

> - Pasting anything into the middle of heading splits it in half (this is expected) and the bottom half loses the style (unexpected).

I couldn't reproduce this either.

By the way, to test the copy/pasting properly you need to do it on a real device. The emulator messes with the data type description and it's always considered a plain text, even if it's styled or HTML.

**Comment by khaykov** [comment]
I'm testing on my Pixel right now, and issues are still there :( Here are exact steps to reproduce them:

> Pasting text (regular text without any block style) ads new line around it.
Open app with demo content, select word "Lorem" and copy it. Select word "Lorem" again and tap "Paste". "Lorem" will move to a separate line. Also, press "Undo" in history and the word "Lorem" will be gone, without any way to return it.

> Inline formatting is not applied to text that is pasted before or after the styled text.
Open app with demo content, select word "Lorem" and copy it. Put cursor right after word "Bold" and paste the word. Notice that "Lorem" goes to the new line and bold is not applied to it.

> Pasting anything into the middle of heading splits it in half (this is expected) and the bottom half loses the style (unexpected).

Open app with demo content, select word "Lorem" and copy it. Put cursor right after "a" in the "Heading 2", paste the word. Notice above mentioned behavior.

Another issue with history - select word "Lorem" and copy it. Paste it in the middle of the word "Bold". Press undo, notice that there is extra space where the word was pasted.

**Comment by 0nko** [comment]
All of the issues above should be addressed with the previous commits. 

A couple of notes:

> Also, press "Undo" in history and the word "Lorem" will be gone, without any way to return it.

Since the original word is replaced with the same one, the text isn't changed so there is no history being recorded.

> Put cursor right after word "Bold" and paste the word. Notice that "Lorem" goes to the new line and bold is not applied to it.

When pasting next to inline styles, the original style is explicitly ignored so that it doesn't affect the pasted text. Say you want to copy a couple of italic words and paste it next to some a bold text. As a user, I'd expect the pasted text to be in the same style as it was copied. I would not expect the 1st word to be bold.

**Comment by khaykov** [comment]
Thank's for the fixes! Everything works as expected now :shipit:

**Pull request merged**
