### PR TITLE
Don't steal focus on initial load of media

### LINKED ISSUE #700: Focus and cursor is lost when switching to visual mode
### Expected
Cursor stays at the input position when switching from html mode to visual mode.

### Observed
Cursor is not visible and focus is not actually in the editor at all.

### Reproduced
1. Run the demo app
2. Switch to html mode
3. Place the cursor at the end of the `Heading 6` text, right before the `</h6> tag
4. Switch back to visual mode and notice that the cursor is lost
5. Type anything on the virtual keyboard and notice that is written nowhere

#### Tested
Nexus 5X on Android v7.1.2 with Aztec v1.3.5

### PR DESCRIPTION
**Pull request by hypest**
### Fix #700 

As part of the work in https://github.com/wordpress-mobile/AztecEditor-Android/pull/349, a workaround was implemented to remove the focus from the editor's View. This PR specializes the workaround to exclude the case when initializing the editor, which happens everytime the user switches from html to visual.

### Test
1. Run the demo app
2. Switch to html mode
3. Place the cursor at the end of the `Heading 6` text, right before the `</h6> tag
4. Switch back to visual mode and notice the cursor blinking at the end of the `Heading 6` line

### CODE REVIEW

**Comment by daniloercoli** [comment]
Should this call to [`refreshText()`](https://github.com/wordpress-mobile/AztecEditor-Android/blob/213f36e6cb3d9b6183ffc21ebe3cefd14b25d6de/wordpress-shortcodes/src/main/java/org/wordpress/aztec/plugins/shortcodes/extensions/VideoPressExtensions.kt#L27) be changed to `refreshText(false)` ?

**Comment by hypest** [comment]
Good catch @daniloercoli , it does seem like we need to change that too. Will do. 🙇‍♂️

**Comment by hypest** [comment]
Fixed with 9577c1f @daniloercoli , ready for another pass. Thanks!

**Comment by daniloercoli** [comment]
Looks good!

**Pull request merged**
