### PR TITLE
Fixing toolbar highlight issues

### LINKED ISSUE #345: Format toolbar buttons only work when device keyboard is open
### Expected

I expect that even if the device keyboard is closed, I can select a format toolbar button, refocus on the editor (to open the keyboard), and the text I type will have the formatting I selected.

### Observed

If I select a format toolbar button while the device keyboard is closed, when I tap again into the editor (even when I tap in the same place where the cursor was already placed) the format toolbar button is deactivated and the text I type has no formatting.

### Reproduced
1. Open the demo app.
2. Remove the demo content.
3. Close the device keyboard. (Note that the cursor remains in the text view.)
4. Tap a format toolbar button (e.g. Bold) to enable it.
5. Tap back into the text view. (The keyboard reappears and the toolbar button is deactivated.)
6. Type text. Result: The text has no formatting.

#### Tested
Nexus 6P API 23 emulator, Aztec demo app (develop branch)

### LINKED ISSUE #357: Inline style in toolbar erroneously highlighted
### Reproduced
1. Load editor without any text.
2. Press Bold button in toolbar.
3. Type somethign and press enter.
4. Deselect Bold and type somethign.
5. Notice that the Bold button is highlighted (but not applied, as expected).

#### Tested
Genymotion on Nexus 6P (7.0.0) and Nesux 5X (6.0.0)

### PR DESCRIPTION
**Pull request by khaykov**
#395 need's to be merged before this one.

Fixes #345
Fixes #357 
Preserves selected style when deleting the last character on 0 index, and allows the selected style to be removed with extra backspace.

### Test 1

1. Open the demo app.
2. Remove the demo content.
3. Close the device keyboard. (Note that the cursor remains in the text view.)
4. Tap a format toolbar button for inline style (e.g. Bold) to enable it.
5. Tap back into the text view. 
6. Confirm that previously selected style in the toolbar is still highlighted.
7. Type text. Confirm that it's correctly styled.

### Test 2

1. Open the demo app.
2. Remove the demo content.
3. Tap a format toolbar button for inline style(e.g. Bold) to enable it.
4. Type text and press enter.
5. Deselect style and type text.
6. Notice that the style button is not highlighted and style is not applied.

### Test 3

1. Open the demo app.
2. Remove the demo content.
3. Tap a format toolbar button for inline style(e.g. Bold) to enable it.
4. Type text.
5. Press backspace to delete all the text.
6. Confirm that selected style is still highlighted.
7. Press backspace.
8. Confirm that selected style is not highlighted.

There are a couple of changes to inline style handling, so it would be awesome if both @0nko and @theck13 could play with inline styles a bit to make sure everything is ok.

### CODE REVIEW

**Comment by khaykov** [comment]
This also fixes #362

**Comment by 0nko** [comment]
For Test 2, after step 4 the style gets deselected automatically. Isn't that intentional?

**Comment by khaykov** [comment]
Yes! It's intentional. Sorry, I copied the steps from the issue without changing them to reflect fixes :)

**Comment by 0nko** [comment]
Nice work! :shipit:

**Pull request merged**
