### PR TITLE
Release v1.5.6

### PR DESCRIPTION
**Pull request by planarvoid**
This branch is used to test the changes made to Aztec editor in other repositories. It contains no changes to the logic, just the `README` update. To test it target: 
`975-e69dca965397a9f2978c8722976bee2f9de597ba ` as the aztec version. 

### Review
@AmandaRiu 
@hypest 

Make sure strings will be translated:

- [x] If there are new strings that have to be translated, I have added them to the client's `strings.xml` as a part of the integration PR.

### CODE REVIEW

**Comment by hypest** [comment]
Unfortunately, I won't have today to attend to this PR so, perhaps @mchowning you can join instead? @planarvoid also had let me know (via Slack) that this is ready to be tested from the gutenberg-mobile side and would like help with creating the gb-mobile and/or Gutenberg PRs to point to this one.

**Comment by mchowning** [comment]
I've created Gutenberg and Android PRs with this change. The WPAndroid PR has builds for testing. I did a bit of testing and didn't see any issues.

- https://github.com/WordPress/gutenberg/pull/40099
- https://github.com/wordpress-mobile/WordPress-Android/pull/16270

**Comment by AmandaRiu** [comment]
Will wait [till this PR is merged](https://github.com/wordpress-mobile/AztecEditor-Android/pull/976) before testing this PR. @planarvoid please let me know when it's ready 👍🏻

**Comment by planarvoid** [comment]
I think this is ready for review/merge @AmandaRiu @mchowning . The version number will actually be `v1.5.7` but I'll add that tag only once this is merged. I've added the `v1.5.6` tag too early and it doesn't include all the changes now.

**Review by AmandaRiu — APPROVED** [review]
:shipit:

**Comment by AmandaRiu** [comment]
This is approved, but unable to merge due to CI failures. Attempting to rerun.

**Comment by AmandaRiu** [comment]
Ah, the build is failing for CI on the step to publish to S3 because 1.5.6 is already published to S3. Going to do a forced merge.

**Pull request merged**
